import mongoose from "mongoose";

const settlementSchema = new mongoose.Schema(
  {
    group: { type: mongoose.Schema.Types.ObjectId, ref: "Group", required: true },
    expense: { type: mongoose.Schema.Types.ObjectId, ref: "Expense" }, // null if generated by "simplify debts"
    from: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true }, // debtor
    to: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true }, // creditor
    amount: { type: Number, required: true },
    status: {
      type: String,
      enum: ["pending", "marked_paid", "cleared"],
      default: "pending",
    },
    clearedAt: { type: Date },
  },
  { timestamps: true }
);

const Settlement = mongoose.model("Settlement", settlementSchema);
export default Settlement;
